[build]
bin = "tmp/bin/server"
pre_cmd = ["rm -rf tmp"]
cmd = "go build -o tmp/bin/server ./cmd/main.go"
include_ext = ["go"]
exclude_dir = ["db/sql", "db/migrations", "logs", "scripts"]
delay = 100
send_interrupt = true
