root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/server"
cmd = "go build -o ./tmp/server ./cmd/main.go"
include_ext = ["go"]
exclude_dir = ["db/sql", "db/migrations", "logs", "scripts"]
exclude_unchanged = true
poll = false
delay = 500
kill_delay = "0s"
send_interrupt = true

[log]
time = true
silent = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
