// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

type Session struct {
	ID     string
	UserID string
}

type User struct {
	ID       string
	Name     string
	Email    string
	Password string
}
