// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"database/sql"
	"time"
)

type Post struct {
	ID        string
	Title     string
	Content   string
	UserID    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Session struct {
	ID         string
	UserID     string
	ValidUntil time.Time
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type User struct {
	ID        string
	Name      string
	Email     string
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
